# Generated by Django 4.2.5 on 2023-09-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='имя')),
                ('date_market_launch', models.DateField(blank=True, null=True, verbose_name='date of market launch')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Retails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('level', models.CharField(choices=[('factory', 'Завод'), ('network', 'Розничная сеть'), ('entrepreneur', 'Индивидуальный предприниматель')], verbose_name='level')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='email')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='city')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='street')),
                ('house_number', models.IntegerField(blank=True, null=True, verbose_name='house number')),
                ('obligation', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='indebtedness to the supplier')),
                ('time_created', models.TimeField(auto_now=True, null=True, verbose_name='creation time')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.products', verbose_name='products')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.retails', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'network model',
                'verbose_name_plural': 'network models',
            },
        ),
    ]
